language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy

before_install: sudo apt-get install -y pandoc

install:
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - hatchery clean test

after_success:
    - cd build_hatchery; coveralls
